// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/10/2026, 11:02:22 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/plugins/**/*.{js,ts,mjs}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/composables/**/*.{js,ts,mjs}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/utils/**/*.{js,ts,mjs}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/app.config.{js,ts,mjs}","/Users/ahmadalghalban/Desktop/cli-firebox/packages/web/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;